module Sections exposing (..)

import Styles exposing (..)
import Css exposing (..)
import Html
import Html.Styled exposing (..)
import Html.Styled.Attributes exposing (css, attribute, href, src, class, id, alt)


section1 : Html msg
section1 = section [ id "site1", class "present"]
                        [ h1 [ class "title" ]
                            [ text "Portfolio" ]
                        , h2 [ class "author" ]
                            [ text "Jagoda \"juliagoda\" Górska" ]
                        , h3 [ class "job" ]
                            [ text "Programistka" ]
                        ]
                        
section2 : Html msg
section2 = section [ id "site2", class "present"]
                        [ h2 []
                            [ text "Krótko o sobie" ]
                        , p [ class "present", id "its-me", firstStyle (sec 2) ]
                            [ text "Jestem od kilku lat programistką C++ i Haskell. Na co dzień zajmuję się nauką nowych technologii oraz metod pracy, wdrażając je do swoich projektów. Jestem także absolwentką Wyższej Szkoły Ekonomii i Informatyki w Krakowie. Moja praca dyplomowa dotyczyła zastosowań języków czysto funkcyjnych w biznesie. Na co dzień używam systemu Linux i to na nim robię wszystko na co dzień, łącznie z pracą nad projektami." ]
                        ]
                        
section3 : Html msg
section3 = section [ class "present", id "i-am-working-hard"]
                        [ h2 [firstStyle (sec 2)]
                            [ text "Podczas pracy daję z siebie wszystko i daje mi to w rezultacie niesamowitą satysfakcję i wiedzę" ]
                        ]

section4 : Html msg                      
section4 = section [ class "present", id "thanks-from-github-1", secondStyle ]
                        [ p [ ]
                            [ img [ src "./juliagoda_portfolio_files/github1.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github2.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github3.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github4.png" ]
                                []
                            ]
                        ]
                        
section5 : Html msg                        
section5 = section [ class "present", id "thanks-from-github-2"]
                        [ p [ secondStyle ]
                            [ img [ src "./juliagoda_portfolio_files/github5.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github6.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github7.png" ]
                                []
                            , br []
                                []
                            , img [ src "./juliagoda_portfolio_files/github8.png" ]
                                []
                            ]
                        ]
                        
section6 : Html msg                     
section6 = section [ class "present", id "visitors-antimicrox-section"  ]
                        [ h3 [  ]
                                [ text "Ruch dla antimicroX" ]
                            , p [ firstStyle (sec 2) ]
                                [ img [ src "./juliagoda_portfolio_files/visitors-antimicrox.png" ]
                                    []
                                ]
                        ]

section7 : Html msg                        
section7 = section [ class "present"  ]
                        [ Html.Styled.table [firstStyle (sec 2)]
                            [ thead []
                                [ tr [ class "header" ]
                                    [ th [  ]
                                        [ text "Aktywności dotyczące C/C++" ]
                                    , th [  ]
                                        []
                                    , th [  ]
                                        []
                                    ]
                                ]
                            , tbody []
                                [ tr [ class "odd" ]
                                    [ td [  ]
                                        [ text "konto na CodeSignal" ]
                                    , td [  ]
                                        [ text "sierpień 2019 - obecnie" ]
                                    , td [  ]
                                        [ a [ href "https://app.codesignal.com/profile/juliagoda" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "even" ]
                                    [ td [  ]
                                        [ text "program QFaktury" ]
                                    , td [  ]
                                        [ text "grudzień 2016 - sierpień 2018" ]
                                    , td [  ]
                                        [ a [ href "https://github.com/juliagoda/qfaktury" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "odd" ]
                                    [ td [ ]
                                        [ text "program antimicroX" ]
                                    , td [  ]
                                        [ text "marzec 2018 - obecnie" ]
                                    , td [  ]
                                        [ a [ href "https://github.com/juliagoda/antimicroX" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "odd" ]
                                    [ td [  ]
                                        [ text "skrypt SDL_JoystickButtonNames" ]
                                    , td [  ]
                                        [ text "kwiecień 2018 - październik 2018" ]
                                    , td [  ]
                                        [ a [ href "https://github.com/juliagoda/SDL_JoystickButtonNames" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                        
section8 : Html msg                        
section8 = section [ class "present"  ]
                        [ Html.Styled.table []
                            [ thead [firstStyle (sec 2)]
                                [ tr [ class "header" ]
                                    [ th [  ]
                                        [ text "Aktywności dotyczące Haskell" ]
                                    , th [  ]
                                        []
                                    , th [  ]
                                        []
                                    ]
                                ]
                            , tbody [firstStyle (sec 2)]
                                [ tr [ class "odd" ]
                                    [ td [  ]
                                        [ text "konto na Exercism" ]
                                    , td [  ]
                                        [ text "od października 2019" ]
                                    , td [  ]
                                        [ a [ href "https://exercism.io/profiles/juliagoda" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "even" ]
                                    [ td [  ]
                                        [ text "skrypt GivenFind" ]
                                    , td [  ]
                                        [ text "marzec 2017 - listopad 2017" ]
                                    , td [  ]
                                        [ a [ href "https://github.com/juliagoda/givenfind" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "odd" ]
                                    [ td [  ]
                                        [ text "program Hasdoc" ]
                                    , td [ ]
                                        [ text "luty 2019 - marzec 2019" ]
                                    , td []
                                        [ a [ href "https://github.com/juliagoda/hasdoc" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                , tr [ class "odd" ]
                                    [ td []
                                        [ text "biblioteka Qtah (jako pomoc dla "
                                        , a [ href "https://gitlab.com/khumba/qtah" ]
                                            [ text "Bryan Gardiner " ]
                                        , text ")"
                                        ]
                                    , td []
                                        [ text "maj 2019 - obecnie" ]
                                    , td []
                                        [ a [ href "https://gitlab.com/juliagoda/qtah" ]
                                            [ text "Link" ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                        
section9 : Html msg                        
section9 = section [ class "present", id "not-only-section"  ]
                        [ aside [ class "present", id "not-only", firstStyle (sec 2) ]
                            [ h4 []
                                [ text "Oczywiście nie tylko znam i nie tylko wiem, co to jest Haskell i C/C++. Jednak zostały przedstawione w formie tabeli, ponieważ pracuję nad nimi na co dzień. " ]
                            ]
                        ]
                        
section10 : Html msg                     
section10 = section [ class "present", id "other-languages" ]
                        [ aside [ class "present", id "other-lang" ]
                            [ h5 []
                                [ text "Z innymi językami i technologiami, jakimi mam/miałam do czynienia to:" ]
                            , ul []
                                [ li [ class "langs", attribute "data-fragment-index" "0", firstStyle (sec 1) ]
                                    [ text "HTML / CSS / Elm -> przy budowie niniejszego portfolio" ]
                                , li [ class "langs", attribute "data-fragment-index" "1", firstStyle (sec 3) ]
                                    [ text "Nginx -> podczas ustawień sieciowych dla portfolio" ]
                                , li [ class "langs", attribute "data-fragment-index" "2", firstStyle (sec 5) ]
                                    [ text "Bash -> jako pomoc przy generowaniu szablonów klas dla Qtah, odblokowanie modułu dla PHP" ]
                                , li [ class "langs", attribute "data-fragment-index" "3", firstStyle (sec 7) ]
                                    [ text "PHP -> do integracji z bazą REGON" ]
                                , li [ class "langs", attribute "data-fragment-index" "4", firstStyle (sec 9) ]
                                    [ text "Python -> do stworzenia szkieletu programu na bazie PyQt5 - "
                                    , a [ href "https://github.com/juliagoda/LabTests" ]
                                        [ text "Link" ]
                                    ]
                                , li [ class "langs", attribute "data-fragment-index" "5", firstStyle (sec 11) ]
                                    [ text "C# -> język wymagany przez 2 lata na uczelni w prawie każdym aspekcie" ]
                                ]
                            ]
                        ]
                        
section11 : Html msg                        
section11 = section [ class "present", id "other-languages-2"  ]
                        [ aside [ class "present", id "other-lang-2" ]
                            [ ul []
                                [ li [ class "langs", attribute "data-fragment-index" "6", firstStyle (sec 1) ]
                                    [ text "Prolog -> zadania na zaliczenie" ]
                                , li [ class "langs", attribute "data-fragment-index" "7", firstStyle (sec 3) ]
                                    [ text "Qt5 na Qt Creator -> pojawia się w większości projektów" ]
                                , li [ class "langs", attribute "data-fragment-index" "8", firstStyle (sec 5) ]
                                    [ text "Docker -> do konteneryzacji aplikacji na X11, Qt5 i C++ - "
                                    , a [ href "https://hub.docker.com/r/juliagoda/antimicrox" ]
                                        [ text "Link" ]
                                    ]
                                , li [ class "langs", attribute "data-fragment-index" "9", firstStyle (sec 7) ]
                                    [ text "Microsoft SQL Server -> z zajęć na uczelni, uzyskanie certyfikatu MTA 98-364: Database Fundamentals" ]
                                , li [ class "langs", attribute "data-fragment-index" "10", firstStyle (sec 9) ]
                                    [ text "Microsoft Visual Studio/Visual Studio Code -> główne narzędzie programowania na uczelni" ]
                                , li [ class "langs", attribute "data-fragment-index" "11", firstStyle (sec 11) ]
                                    [ text "XML / YAML / JSON -> sposoby przechowywania danych w aplikacjach" ]
                                , li [ class "langs", attribute "data-fragment-index" "12", firstStyle (sec 13) ]
                                    [ text "CMake -> przy aplikacjach związanych z C/C++" ]
                                , li [ class "langs", attribute "data-fragment-index" "13", firstStyle (sec 15) ]
                                    [ text "git / Github / GitLab -> używane na co dzień" ]
                                ]
                            ]
                        ]
                        
section12 : Html msg                      
section12 = section [ class "present", id "creating-tutorials"  ]
                        [ aside [ class "present", id "make-tut", firstStyle (sec 2) ]
                            [ h4 []
                                [ text "Sprawdzam się także przy przygotowywaniu materiałów dydaktycznych, dokumentacji oraz tutoriali " ]
                            , p [  ]
                                [ a [ href "https://github.com/juliagoda/hasdoc/blob/master/doc/doc-pl.pdf" ]
                                    [ text "Dokumentacja" ]
                                ]
                            , p [  ]
                                [ a [ href "https://github.com/juliagoda/CH341SER" ]
                                    [ text "Tutorial" ]
                                ]
                            , p [  ]
                                [ a [ href "https://github.com/juliagoda/givenfind" ]
                                    [ text "Opis działania" ]
                                ]
                            , p [  ]
                                [ a [ href "https://github.com/juliagoda/HowToNameIt/tree/master/Haskell" ]
                                    [ text "Zbiór schematów" ]
                                ]
                            ]
                        ]
                        
section13 : Html msg                      
section13 = section [ class "present", id "visitors-tutorial-section", secondStyle  ]
                        [ aside [ class "present", id "visitors-tutorial" ]
                            [ h3 []
                                [ text "Ruch dla tutorialu" ]
                            , p [  ]
                                [ img [ src "./juliagoda_portfolio_files/visitors-tutorial.png" ]
                                    []
                                ]
                            ]
                        ]
                        
                        
section14 : Html msg                       
section14 = section [ class "present", id "why-it-quest"  ]
                        [ aside [ class "present", id "why-it-question", firstStyle (sec 2) ]
                            [ h2 []
                                [ text "Dlaczego akurat IT?" ]
                            ]
                        ]
                        
section15 : Html msg                      
section15 = section [ class "present", id "why-it-section"  ]
                        [ p [ class "present", id "why-it", firstStyle (sec 2) ]
                            [ text "Generalnie rzecz biorąc, to od zawsze fascynował mnie świat technologiczny. Jako nastolatkę z początku fascynowały mnie struktury konsol do gier, gamepadów. Mając 18 lat pierwszy raz zdobyłam się na odwagę by zainstalować dystrybucję Linux. Do tej pory używałam Linux Mint, Debian Testing, Ubuntu, Manjaro, a od kilku lat pozostałam przy Arch Linux.W 2014 roku zdecydowałam, że wyspecjalizuję się w programowaniu. Fakt, że tylko wyobraźnia ogranicza programowanie czegokolwiek sprawiał, że wybrałam tę część informatyki, by tworzyć i naprawiać. " ]
                        ]
                        
section16 : Html msg                        
section16 = section [ class "present", id "why-it-section-2"  ]
                        [ p [ class "present", id "why-it-2", firstStyle (sec 2) ]
                            [ text "Pierwszym moim materiałem do nauki pierwszego języka programowania była książka Larry'ego Ullman'a pod tytułem \"Nowoczesny język JavaScript\". Rok później zapisałam się na studia, które ukończyłam z oceną bardzo dobrą za pracę dyplomową jak i średnią z ocen.Podczas trwania studiów miałam okazję zrozumieć dokładniej, czym są algorytmy, zrozumieć jak wygląda w praktyce programowanie programatora z pomocą Arduino oraz łączenie komponentów elektronicznych, poznać Business Intelligence na przykładzie wybranego zbioru danych, jak wygląda i działa baza danych na systemie Windows i więcej." ]
                        ]
                        
section17 : Html msg                        
section17 = section [ class "present", id "cv-jg-section" ]
                        [ aside [ class "present", id "cv-jg", firstStyle (sec 2) ]
                            [ h2 []
                                [ text "Moje CV" ]
                            , h2 [ ]
                                [ a [ href "https://interviewme.pl/cv/jagoda-gorska-cplusplus" ]
                                    [ text "PL" ]
                                ]
                            , h2 [ ]
                                [ a [ href "https://interviewme.pl/cv/jagoda-gorska-en-complex" ]
                                    [ text "EN" ]
                                ]
                            ]
                        ]
                        
section18 : Html msg                      
section18 = section [ class "present", id "contact-me-section"  ]
                        [ aside [ class "present", id "contact-me" ]
                            [ h2 []
                                [ text "Kontakt" ]
                            , p [ firstStyle (sec 2) ]
                                [ text "juliagoda.pl@protonmail.com" ]
                            ]
                        ] 
